---
# Production environment group variables

# Environment-specific variables
environment: prod
domain: homelab.local
cluster_name: prod-cluster
datacenter: prod-dc
backup_enabled: true
monitoring_enabled: true
logging_level: warn

# Network configuration
network:
  cidr: "192.168.3.0/24"
  gateway: "192.168.3.1"
  dns_servers: ["192.168.3.1", "8.8.8.8"]

# Proxmox configuration
proxmox:
  api_url: "https://192.168.3.102:8006"
  storage_pool: "local-zfs"
  vm_template_path: "/var/lib/vz/template/iso/"
  
# Kubernetes configuration
kubernetes:
  version: "1.28"
  cni: "cilium"
  pod_cidr: "10.246.0.0/16"
  service_cidr: "10.98.0.0/12"
  
# Terraform configuration
terraform:
  state_backend: "local"
  workspace: "prod"
  provider_version: ">= 3.0"
