---
# OpenWrt Router Configuration for rt-1-cluster
# Specific configuration for this router instance

# Network Configuration
cluster_ip: "10.10.0.200"
cluster_netmask: "255.255.255.0"

# Router-specific packages
packages_to_install:
  - "luci"
  - "luci-app-firewall"
  - "luci-app-opkg"
  - "luci-app-system"
  - "luci-app-network"
  - "luci-app-dhcp"
  - "luci-app-statistics"
  - "luci-app-wireless"

# Custom firewall rules for this router
custom_firewall_rules:
  - name: "Allow-SSH-From-Management"
    src: "wan"
    proto: "tcp"
    dest_port: "22"
    target: "ACCEPT"
  
  - name: "Allow-HTTP-From-Management"
    src: "wan"
    proto: "tcp"
    dest_port: "80"
    target: "ACCEPT"
  
  - name: "Allow-HTTPS-From-Management"
    src: "wan"
    proto: "tcp"
    dest_port: "443"
    target: "ACCEPT"

# Port forwarding rules (if needed)
port_forwarding:
  - name: "SSH-Forward"
    src: "wan"
    dest: "lan"
    proto: "tcp"
    src_port: "2222"
    dest_ip: "10.10.0.10"
    dest_port: "22"

# DHCP hosts for static assignments
dhcp_hosts:
  - name: "talos-cp-01"
    mac: "aa:bb:cc:dd:ee:01"
    ip: "10.10.0.10"
  - name: "talos-cp-02"
    mac: "aa:bb:cc:dd:ee:02"
    ip: "10.10.0.11"
  - name: "talos-cp-03"
    mac: "aa:bb:cc:dd:ee:03"
    ip: "10.10.0.12"
  - name: "talos-worker-01"
    mac: "aa:bb:cc:dd:ee:11"
    ip: "10.10.0.20"
  - name: "talos-worker-02"
    mac: "aa:bb:cc:dd:ee:12"
    ip: "10.10.0.21"
  - name: "talos-worker-03"
    mac: "aa:bb:cc:dd:ee:13"
    ip: "10.10.0.22"

# DNS records for cluster services
dns_records:
  - name: "talos-api"
    ip: "10.10.0.10"
  - name: "talos-dashboard"
    ip: "10.10.0.10"
  - name: "kubernetes"
    ip: "10.10.0.10"

# Monitoring configuration
monitoring:
  enabled: true
  snmp:
    enabled: true
    community: "talos-cluster"
    location: "Development Cluster Router"
    contact: "admin@dev-talos.local"

# Backup configuration
backup_enabled: true
backup_retention_days: 7  # Keep backups for 1 week in dev
backup_schedule: "0 3 * * *"  # Daily at 3 AM

