#cloud-config
users:
  - name: root
    ssh_authorized_keys:
      - ${ssh_public_key}

# Talos worker configuration
write_files:
  - path: /etc/talos/config.yaml
    content: |
      version: v1alpha1
      debug: false
      persist: true
      machine:
        type: worker
        token: "your-bootstrap-token-here"
        ca:
          crt: ""
          key: ""
        certSANs: []
        kubelet:
          image: ""
        network:
          hostname: "${cluster_name}-worker-${node_index + 1}"
          interfaces:
            - interface: eth0
              addresses:
                - 10.0.0.${node_index + 20}/24
        install:
          disk: /dev/vda
          image: ghcr.io/siderolabs/installer:${talos_version}
        sysctls:
          net.core.somaxconn: 65535
          net.ipv4.ip_local_port_range: "1024 65535"
          net.ipv4.tcp_rmem: "4096 12582912 12582912"
          net.ipv4.tcp_wmem: "4096 12582912 12582912"
          net.core.netdev_max_backlog: 5000
        kubelet:
          extraArgs:
            rotate-server-certificates: true
      cluster:
        name: ${cluster_name}
        controlPlane:
          endpoint: https://10.0.0.10:6443
        clusterName: ${cluster_name}
        network:
          dnsDomain: cluster.local
          podSubnet: 10.244.0.0/16
          serviceSubnet: 10.96.0.0/12
        proxy:
          disabled: false
        discovery:
          enabled: true
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: false
        token: "your-bootstrap-token-here"
        ca:
          crt: ""
          key: ""
        aggregatorCA:
          crt: ""
          key: ""
        serviceAccount:
          crt: ""
          key: ""
        aescbcEncryptionSecret: ""
        secretboxEncryptionSecret: ""

runcmd:
  - systemctl enable talos
  - systemctl start talos