collections:
  - name: ansible.posix
    version: ">=2.1.0"
  - name: community.general
    version: ">=11.3.0"
  - name: community.sops
    version: ">=2.2.2"
  - name: community.proxmox
    version: "<=1.2.0"