[global]
keyboard = "fr"
country = "fr"
fqdn = "pve02.homelab.local"
mailto = "admin@homelab.local"
timezone = "Europe/Paris"
root-password = "ChangeMe123!" # will be overwritten by postinstall. Using a production password will lead to be a security issue
root-ssh-keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj4+K9NTlK6d39HJkU+w0h51qCrCaE87K8GZ+vNzJwLw1KL9D/zoKPEVyJSrOZIlea0bPlYrM/Kv+3GaScIDPpKAn+V8BkPWpUaQcSyqMCJe61RYWvEO8iiL55ZKzRZcsfLBUxpNh0F96HYKMtiy+Kx5FJn5gXOqGS0cWZteYo1RpQ1Dy3BxwlU51pCP8Mk13axoth9BI7VBO3o/2G/CJOKMrFDuFyJiQBb47JeebYyzbwZJSQnNxvq21Xsh/IFsgavAmGw76wGtC3wEdgWJuCNDyRfLeOX1Vk/oaLV9EHmbeJuLFO10HO9DrJyLW9FBIL7OfqEW+Yk9ekXtbaU83+sh1vE2UBCghMn3Ahi9wWenIFqQ3ZudmJ4TNSrWNFxnPv9OKdwSxnbvBSB7rjiMA7CfKYB0OeYUskHLRU1Y8kRancjKkP1aVgNKHSB5Q7/20x33F5QnSpS32Pc3KvYdv1Q7IloaFwHfFwWo2CX6fyAdfyCPMZuctz6j9DOT8lTrs= skorll@Odin"
]
reboot-on-error = false
reboot-mode = "reboot"

[network]
source = "from-answer"
cidr = "192.168.0.149/24"
dns = "1.1.1.1"
gateway = "192.168.0.254"
filter.ID_NET_NAME = "enp2s0"

[disk-setup]
filesystem = "zfs"
zfs.raid = "raid0"
zfs.hdsize = 220
zfs.ashift = 12
zfs.arc-max = 1024
zfs.checksum = "on"
zfs.compress = "lz4"
zfs.copies = 1
filter.ID_MODEL = "SanDisk_SSD_PLUS_240GB"
filter-match = "any"

# [first-boot]
# source = "from-iso"
# ordering = "fully-up"
# Note: First-boot provisioning handled by Ansible
