---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: traefik
spec:
  encryptedData:
    credentials.json: AgAuTbt88ZPlkFBdOl5Zil/g+T3MbYNoARtFAVDaFw1E/fr+7R9EmPZhfzVFzfjxXEk2IWtPUVJpZvyvHuUa1DjodwNVAa+xehtaEH232J6jUYX7fKxwzm7mVbAX0aPlz1o5aIyaQkrAQA6Y7WRysdhwsOf2/0wIR/CHF7HpY9A96DZIbfGCYzdhJKdj8Q4LuFZyimfa/czkyVQTppeHg6eUoD0HXkEjN6QmUo9pbNPtrgxvHv4eXA77+7d9iEeM3KkU22uhFCufBaFFNQ6rzCR0jEwaW2RX8GvlA39cAk2SllYKi/qveiXOilh4i+E2pn0Q11Dby/otOPJ6MEBtgT9hQMD+gRB8YZj7sT7mWs4YncmxdLetbo6Yz/gpQ+BqOYNdXQglQGtCck4iNYDlR08ZKhpAQQXiIMY/O6+b12bVql9YEpGBR6bZkD81dE/YFRy9L0lkn9Rvc7vLByrbE+gzm7g7ZY46XDfXNnpuKQDdsFEQPOxsPe8iTsqdzqzVSBrPOZW4VpmY9nZJLKrsT9clBY+DHpttMpp3+hKbeBoQKQ6Wx1R0+w0vyXzPfM1KIIu7bGpFbpAtE4i99XBEMpXiNMyban99PRxjViFulwtsB8gQLkIs9m2pgZwf/OEq3h2BJ2bb9eDYKzrtBdBIsiF5tSn6J9thMfdxxxhOeXRWwlcSO9rjAeAOgmS49/y/QHelfrTRCfYwiK09nUbEwshwCC0AhwT/Za/GFs5TcDTqQZA2QBfHhTMuu/Al+P2bgV6wmsK48UUTpzOOtQrZNI/QmuOBavOIBhA0fOEJVH/XUdmfUnIWPaIJWkRoYIxOIKHEKGwUXdNdKEcAdPwyOM3CAsPH9ksorcT9eE3Tyv5wB8WHDrUd2LiQJS/DAsLPLr4JmqKgzs4LuO3b/U7ZuTKNnA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: traefik