---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: traefik
spec:
  encryptedData:
    credentials.json: AgBgkJRX+7A7zcAA2Yjrc/w0kfLnD7eFh4KVx3I4cM/WMhkq0xvavbucldYRZmC8pdJrzWY0gOTQhgx0Ql8wMiuXTbHnW0geHQGH+gXUz9nkFkbFHiiACAHVz2I0OYioZEoFcUKvSmp0JANrBXFdf6B5hmgxerogNNvzooE8B9fhDDBDIGCScaKbP93qBDn6RjDM1kh3jM795WMQvsmVGB1ogfhve5cznlB7Hp4nSQHTBSt35RLdGpY7lnBS3fioITybxiRxTdb5FCllAEYK2uoKHfZ359pJwFnunDhmplA29Z2S46wRe6y/3iKdnqoT02JEMHD7lrONB+8fDB6225GfHX2FtsuT9d22S/ua7EcOfR14w7p0CIcskhM+8dQKDQbSqA9xHlqIUFZlpcOgpdrZXxqIR/vTIM+LRjf+LTzZk9RNNelniFgrN1DiHK51UjbM3OqUWrUR9gILmPqVxVxQrfBeLyBCEZHQaCgCh1LmStMd0sIcY8Pe3M1sYT4qFO4+CsRzhLJUNVH9xQgCLWwvxlD4p/4N175uoOJPDCZ7jWs/WCr4F/ERl2OvGPsLCXUuTS4ocVRWRCUUL2cyOJrpTdv/MZrlID7VieQP4lavSk2OHa35xV4fXRM9KpDQRcnKKCi4cWT8H8X6VlvvkbulY54GuFLamM+3A6q2rTZj+mPf4V2d2HmbYvKSeRWk0hJ4GPojvFrezV5aUAM0kiM+ZjlbM1sdA26BlZQ5OR5dJwtrxhrv/ZMPa0mtgpF8V0pGqv0FSDA9jVikN7LEpECm+RcR4043wWllFraeWPCsUAgO9sF2e1UAE9lN2dKowFIE/xicVVwFmzAvg8V1c5mIvCfB8Pyif+P+UsEHSNW6akGg7hIAzOHLot14Cm2rx3h2FuLhmTlmg2pljRsclKmikw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: traefik