apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m
  values:
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`n8n.piernas.fr`)
        entryPoints: ["web"]
        middlewares:
          - name: traefik-dashboard-auth
    additionalArguments:
      - "--entrypoints.websecure.http.tls.certresolver=default"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--certificatesresolvers.default.acme.email=your-email@example.com"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
    certificatesResolvers:
      default:
        acme:
          email: your-email@example.com
          storage: /data/acme.json
          tlsChallenge: {}
          domains:
            - main: "traefik.traefik.svc.cluster.local"
    volumes:
      - name: traefik-cert
        secret:
          secretName: traefik-cert
    volumeMounts:
      - mountPath: "/certs"
        name: traefik-cert
        readOnly: true

    # Create the custom middlewares used by the IngressRoute dashboard (can also be created in another way).
    # /!\ Yes, you need to replace "changeme" password with a better one. /!\
    extraObjects:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: traefik-dashboard-auth-secret
          namespace: traefik
        type: kubernetes.io/basic-auth
        stringData:
          username: admin
          password: changeme

      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: traefik-dashboard-auth
          namespace: traefik
        spec:
          basicAuth:
            secret: traefik-dashboard-auth-secret