---
# Staging Environment Inventory
# This file defines all hosts and groups for the staging environment

all:
  children:
    staging:
      children:
        # Proxmox VE hosts
        staging_pve:
          hosts:
            pve02-staging:
              ansible_host: 192.168.2.102
              ansible_user: root
              environment: staging
              cluster_role: pve
              datacenter: staging-dc
              terraform_vars:
                proxmox_node: "pve02"
                storage_pool: "local-zfs"
                cluster_name: "staging-cluster"
                vm_id_start: 200
                vm_memory: 6144
                vm_cores: 4
                vm_disk_size: "64G"
                vm_network: "vmbr0"
                vm_template: "talos-v1.7.0"
                vm_tags: "staging,homelab"
        
        # Kubernetes cluster hosts
        staging_k8s:
          children:
            staging_k8s_control:
              hosts:
                staging-k8s-cp-01:
                  ansible_host: 192.168.2.110
                  ansible_user: root
                  environment: staging
                  cluster_role: control-plane
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 210
                    vm_memory: 6144
                    vm_cores: 4
                    vm_disk_size: "32G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,control-plane"
                    talos_config_type: "controlplane"
                
                staging-k8s-cp-02:
                  ansible_host: 192.168.2.111
                  ansible_user: root
                  environment: staging
                  cluster_role: control-plane
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 211
                    vm_memory: 6144
                    vm_cores: 4
                    vm_disk_size: "32G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,control-plane"
                    talos_config_type: "controlplane"
                
                staging-k8s-cp-03:
                  ansible_host: 192.168.2.112
                  ansible_user: root
                  environment: staging
                  cluster_role: control-plane
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 212
                    vm_memory: 6144
                    vm_cores: 4
                    vm_disk_size: "32G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,control-plane"
                    talos_config_type: "controlplane"
            
            staging_k8s_workers:
              hosts:
                staging-k8s-worker-01:
                  ansible_host: 192.168.2.120
                  ansible_user: root
                  environment: staging
                  cluster_role: worker
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 220
                    vm_memory: 16384
                    vm_cores: 8
                    vm_disk_size: "100G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,worker"
                    talos_config_type: "worker"
                
                staging-k8s-worker-02:
                  ansible_host: 192.168.2.121
                  ansible_user: root
                  environment: staging
                  cluster_role: worker
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 221
                    vm_memory: 16384
                    vm_cores: 8
                    vm_disk_size: "100G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,worker"
                    talos_config_type: "worker"
                
                staging-k8s-worker-03:
                  ansible_host: 192.168.2.122
                  ansible_user: root
                  environment: staging
                  cluster_role: worker
                  cluster_name: staging-cluster
                  node_type: talos
                  terraform_vars:
                    proxmox_node: "pve02"
                    vm_id: 222
                    vm_memory: 16384
                    vm_cores: 8
                    vm_disk_size: "100G"
                    vm_network: "vmbr0"
                    vm_template: "talos-v1.7.0"
                    vm_tags: "staging,k8s,worker"
                    talos_config_type: "worker"
        
        # Staging services
        staging_services:
          hosts:
            staging-gitlab:
              ansible_host: 192.168.2.130
              ansible_user: root
              environment: staging
              cluster_role: service
              service_type: gitlab
              terraform_vars:
                proxmox_node: "pve02"
                vm_id: 230
                vm_memory: 8192
                vm_cores: 4
                vm_disk_size: "80G"
                vm_network: "vmbr0"
                vm_template: "ubuntu-22.04"
                vm_tags: "staging,services,gitlab"
            
            staging-monitoring:
              ansible_host: 192.168.2.131
              ansible_user: root
              environment: staging
              cluster_role: service
              service_type: monitoring
              terraform_vars:
                proxmox_node: "pve02"
                vm_id: 231
                vm_memory: 4096
                vm_cores: 4
                vm_disk_size: "60G"
                vm_network: "vmbr0"
                vm_template: "ubuntu-22.04"
                vm_tags: "staging,services,monitoring"
      
      vars:
        # Environment-specific variables
        environment: staging
        domain: staging.homelab.local
        cluster_name: staging-cluster
        datacenter: staging-dc
        backup_enabled: true
        monitoring_enabled: true
        logging_level: info
        
        # Network configuration
        network:
          cidr: "192.168.2.0/24"
          gateway: "192.168.2.1"
          dns_servers: ["192.168.2.1", "8.8.8.8"]
        
        # Proxmox configuration
        proxmox:
          api_url: "https://192.168.2.102:8006"
          storage_pool: "local-zfs"
          vm_template_path: "/var/lib/vz/template/iso/"
          
        # Kubernetes configuration
        kubernetes:
          version: "1.28"
          cni: "cilium"
          pod_cidr: "10.245.0.0/16"
          service_cidr: "10.97.0.0/12"
          
        # Terraform configuration
        terraform:
          state_backend: "local"
          workspace: "staging"
          provider_version: ">= 3.0"